shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path('product/<slug:slug>', views.product_detail_view, name='detail'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/delete/<slug:slug>', views.delete_item_view, name='delete'),
    path('order/', views.order_view, name='order'),
    path('order/created/', TemplateView.as_view(template_name='order-created.html'), name='order-created'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    
    <link href="{% static "css/base.css" %}" rel="stylesheet">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    

</head>
<body>

    <!-- Messages -->
    {% if messages %}
    <div class="row">
      <div class="col-sm-12">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
          </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">
            <a href="{% url 'shop:list' %}">Shop</a>
        </h5>
        <div class="cart">
            {% if cart_items %}
                You have {{cart_items}} item{{cart_items | pluralize}} in <a href="{% url 'shop:cart' %}">cart</a>
            {% else %}
                Your cart is empty.
            {% endif %}
        </div>
    </div>

    
    <div id="content" class="container">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-6 col-md">
                <h5>Footer</h5>
            </div>
        </div>
    </footer>

    <!-- Bootstrap js-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
    <h3>Cart</h3>

    {% if objects_list %}
    <div class="card-deck mb-3 text-center">
    {% for item in objects_list %}
        <div class="card" style="width: 18rem;">
            <div class="card-image">
                <!--class card-img-top-->
                <img src="{{item.image.url}}" alt="item.slug">
            </div>
            <div class="card-body">
                <b>{{item.name | capfirst}}</b>
                <p class="card-text">Quantity: {{item.item_count}} </p>
                <p class="card-text">Price: {{item.price}} </p>
            </div>
            <p>
                <tr>
                    <td>
                        <a href="{% url 'shop:delete' item.slug %}" class="btn btn-primary">Delete</a>
                    </td>
                    <td>
                        <a href="{% url 'shop:detail' item.slug %}?quantity={{item.item_count}}" class="btn btn-primary">Change</a>
                    </td>
                </tr>
            </p>
        </div>
    {% endfor %}
    </div>
    <div class="center">
        <p>Total price: {{total_price}}</p>
        <p><a href="{% url 'shop:order' %}" class="btn btn-primary">Order</a></p>
    </div>
    {% else %}
    <p>Cart is empty.</p>
    {% endif %}

</div>
{% endblock content %}

templates/order-created.html
{% extends 'base.html' %}

{% block content %}
<h1>Succes</h1>
<p>Your order processing now, please wait, our manager will contact you.</p>
{% endblock content %}

templates/order.html
{% extends 'base.html' %}

{% block content %}
<div class="form-group">
    <form action="" method="post">
        {% csrf_token %}
        {{order_form.as_p}}
        <strong>Total price: {{total_price}}</strong>
        <p><input type="submit" value="Order" class="btn btn-primary"></p>
    </form>
</div>
{% endblock content %}

templates/product-detail.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2>{{product.name}}</h2>
    <img src="{{product.image.url}}" alt="{{product.slug}}" class="detail-image"> 
    <p>Price: {{product.price}}</p>
    <h3>Description</h3>
    <p>{{product.description}}</p>
    <form action="" method="post">
        {% csrf_token %}
        <table class="table">
            <tr>
                <td>
                    {{form.as_p}}
                </td>
                <td>
                    <input type="submit" value="Add to cart" class="btn btn-primary"> 
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock content %}

templates/products-list.html
{% extends 'base.html' %}


{% block content %}


<div id="sidebar" class="filter-sidebar">
    <h3>Categories</h3>
    <form method="get">
        <div class="list-unstyled mt-3 mb-4">
        {{ filter.form }}
        </div>
        <input type="submit" class="btn btn-sm btn-block btn-primary" value="Filter"/>
    </form>
</div>


<div class="card-deck mb-3 text-center">
    
    {% for product in filter.qs %}
    <div class="card mb-4 shadow-sm card">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{product.name}}</h4>
      </div>
      <div class="card-body">
        <div class="bd-placeholder-img card-img-top card-image"><img src="{{product.image.url}}" alt="{{product.slug}}" ></div>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Price: {{product.price}}</li>
        </ul>
        <a href="{% url 'shop:detail' product.slug %}" class="btn btn-lg btn-block btn-primary">Detail</a>
      </div>
    </div>
    {% endfor %}

  </div>

{% endblock content %}

templates/remove-item.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete item?</h1>
    <p>Please confirm that you want to delete item {{item}}.</p>
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-primary">
    </form>
{% endblock content %}